Repository calpoly-csai/api, pull requests merged in 2020-05, with the labels that each got.

#147 Flask app new wakeword data endpoint tests
  flask_api.py
  tests/test_flask_api.py
Labels: testing

#148 AudioMetadata lives again!!!!
  Entity/AudioSampleMetaData.py
  database_wrapper.py
  flask_api.py
  modules/validators.py
  tests/test_database_wrapper.py
  tests/test_flask_api.py
  tests/test_validators.py
Labels: enhancement

#157 Merge init_db and init_nimbus and add pre-ping
  flask_api.py
Labels: bug
